version: '3.8'

volumes:
  mongo_vol:

networks:
  produto_net:
    driver: bridge

services:
  api:
    image: andreameinhart/api-produto:${TAG}
    build:
      dockerfile: ./Dockerfile
      context: ./src
    ports:
      - 8080:8080
    networks:
      - produto_net
    depends_on:
      - condescending_hermann
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@condescending_hermann:27017/admin

  condescending_hermann:
    image: mongo:4.4.3
    ports:
    - 27017:27017
    networks:
      - produto_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd